apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website-test
  template:
    metadata:
      labels:
        app: static-website-test
    spec:
      volumes:
        - name: website
          emptyDir: {}
      initContainers:
        - name: clone-website
          image: node:20-alpine
          workingDir: /mnt
          command:
            - sh
            - -c
            - |
              apk add --no-cache git && \
              git clone --depth 1 https://github.com/atxpaul/example-website.git . && \
              npm install && \
              npm run build
          volumeMounts:
            - name: website
              mountPath: /mnt
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website
              mountPath: /usr/share/nginx/html
              subPath: dist
