name: Main

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            workflow_title:
                description: 'Title for workflow'
                required: false
                default: 'Main Workflow'

run-name: ${{ inputs.workflow_title }}

jobs:
    lint:
        uses: ./.github/workflows/_lint.yml
        secrets: inherit

    unittest:
        uses: ./.github/workflows/_unittest.yml
        secrets: inherit
        needs: [lint]

    deploy:
        uses: ./.github/workflows/_deploy.yml
        if: github.event_name != 'pull_request'
        secrets: inherit
        needs: [unittest]
